backend:
  name: github
  repo: твой-username/твой-репозиторий
  branch: main

media_folder: images

collections:
  - name: courses
    label: Курсы
    folder: _courses
    create: true
    fields:
      - { label: Название, name: title, widget: string }
      - { label: Цена, name: price, widget: string }
      - { label: Длительность, name: duration, widget: string }
      - { label: Категория, name: category, widget: select, options: [children, adults] }
      - { label: Описание, name: description, widget: text }
